name: Create tag and release

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Version name in the format "[major].[minor].[patch]", where major, minor and patch are numeric. Will be used in tag name and in release name.'
          required: true
          type: string

permissions:
  contents: write

jobs:
  release:
    name: Tag and release
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with: 
            ref: 'main'
        - name: Create and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}  
            custom_tag: ${{ inputs.version }} 
        - name: Create archive    
          run: zip -r 'govuk-moodle-theme.zip' ./TodoApi    
        - name: Create release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}
            artifacts: "govuk-moodle-theme.zip"
            generateReleaseNotes: true