name: Create tag and release

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Version name in the format "[major].[minor].[patch]", where major, minor and patch are numeric. Will be used in tag name and in release name.'
          required: true
          type: string

permissions:
  contents: write

jobs:
  compile-scss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile SCSS to CSS
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: "scss/govuk.scss"
          destination: "style/govuk.css"
          minify: true  

      - name: Commit and push compiled CSS
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add style/govuk.css
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-compiled SCSS"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Tag and release
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with: 
            ref: 'main'
        - name: Create and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}  
            custom_tag: ${{ inputs.version }} 
        - name: Create archive    
          run: zip -r 'govuk-moodle-theme.zip' ./govuk    
        - name: Create release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}
            artifacts: "govuk-moodle-theme.zip"
            generateReleaseNotes: true